### ISSUE TITLE
Is Possibility to sync signature into file

### ISSUE THREAD

**Issue by cedricmeschin** [kam193/thbrd-signature#6]
Hi,
Is it possible to sync signature into file instead of directly in messages?

Kind regards

**Comment by kam193** [comment]
Hi,
Do you want to have a file that contains the code of your signature? I think it should be technically possible, although it may require very broad permissions (https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions - usually extensions shouldn't have free access to your files, and the only one granular permission is to access downloaded files). I don't feel like doing it. What do you need it for? Maybe we could find an easier way to address your use case?

**Comment by cedricmeschin** [comment]
OK I get it.
Thunderbird is my main application for emails.
I have third party applications that can send emails and that need to contain my signature. These applications like Thunderbird can support a signature via a file.
I thought I could synchronize the signature via this extension to share it with the other applications.
I'll see if it's possible to do it differently.
Thanks for the quick answer.
Sincerely

**Comment by kam193** [comment]
Hi,
yeah, unfortunately, I think it could be a little tricky to integrate it into this add-on. This is a special case; but if you're familiar with JavaScript basics, maybe you could write a simple add-on, that would just save a current signature to the file, and use it locally. Used in parallel with my add-on, it should work, possibly with some delay.

I think that from Thunderbird API you just need to use [accounts](https://webextension-api.thunderbird.net/en/latest/accounts.html) and [identities](https://webextension-api.thunderbird.net/en/latest/identities.html) objects, and then save the signature in a file.

**Comment by cedricmeschin** [comment]
thank you for the research leads.

**Comment by kam193** [comment]
No problem, hope you solve your case!

**Comment by JohnLGalt** [comment]
Just had a thought - so the addon itself never creates any sort of files locally, anywhere? Not even temporary files?

Just curious, not making any sort of accusation or trying to start a fight....

**Comment by kam193** [comment]
Exactly, the add-on is using just the local storage - this is the feature from Thunderbird (and any browser). The Thunderbird is responsible for storing it (and isolating from other add-ons). I've never verified what technology is used under the hood, but I think it's most probably SQLite database. But the add-on has no direct access to files, this is fully managed by the MailExtension API. I use this script to save data: https://github.com/thundernest/addon-developer-support/blob/09e1c5bb499f720659a52f2ce07b61339f7dc6b7/scripts/preferences/preferences.js

In the first version, the add-on needed so-called "full access" permission because the signature access wasn't available through the official API. As soon as signatures were incorporated into the official API, the add-on was updated to use it - and permission scope was limited to only necessary ones. Thanks to this, the Thunderbird ensures that it never access anything more than account identities (which handles signatures) and data from Google websites (for OAuth authorization and Gmail API access). Any try to access something more would be blocked.

**Comment by JohnLGalt** [comment]
Ahh, therein lay my error - not direct access to local files from the addon itself, only through Thunderbird.

Thanks for the explanation!
